---
title: Opvulling (padding) en marges (margins)
hero_image: images/banner.png
description: Opvulling (padding) en marges (margins).
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Opvulling (padding) en marges (margins)
