title: Padding and margins
hero_image: images/banner.png
description: Padding and margins
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Padding and margins
